[package]
name = "puzzle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3
debug = 0
strip = true
lto = true

[dependencies]
itertools = "0.10.5"
rand = "0.8.5"
